### ISSUE TITLE
Filtering/search

### ISSUE THREAD

**Issue by moseleyi** [crudlio/crudl-example-express#13]
I had a look at the entries.js to find out how to implement search. 

I can see this code:

```
{
name : 'search',
label : 'Search',
field : 'Search',
helpText : 'Title'
}
```

but can't find how it's implemented on GraphQL server side?

**Comment by sehmaschine** [comment]
definitely not the best solution with GraphQL, but see:
https://github.com/crudlio/crudl-example-express/blob/master/blog/graphql/schema.js#L222
