### ISSUE TITLE
Pagination with pages

### ISSUE THREAD

**Issue by moseleyi** [crudlio/crudl-example-express#14]
In your example for Entries I can see page numbers. How to implement it? Also is it only if all the data is loaded, in other words I have to load all the data and then specify some pages, or does it only execute API call for a certain page? I can't find anything in entries.js

**Comment by sehmaschine** [comment]
Pagination is done with a middleware for connectors:
https://github.com/crudlio/crudl-example-express/blob/master/crudl-admin-rest/admin/connectors/middleware/numberedPagination.js

See also:
https://github.com/crudlio/crudl#pagination

It depends on how your API deals with pagination. With our example, we use express-paginate:
https://github.com/crudlio/crudl-example-express/blob/master/blog/rest/api.js#L2
