### ISSUE TITLE
No token provided error on crudl-graphql admin

### ISSUE THREAD

**Issue by ellipticaldoor** [crudlio/crudl-example-express#4]
I get the following response when trying to access to http://localhost:3000/crudl-graphql as in the documentation says:

```
{
    "success": false,
    "message": "No token provided."
}
```

**Comment by vam** [comment]
A trailing slash is required: http://localhost:3000/crudl-graphql/

Please close this issue, if that solved your problem.

**Comment by ellipticaldoor** [comment]
Okay, now it works. Thanks.

**Comment by ellipticaldoor** [comment]
This behaviour can be fixed? Y a user remove the slash is going to break the admin

**Comment by vam** [comment]
It's a matter of server configuration which is currently strict on the slashes. We'll look into that and consider changing that behavior in the next release. 

Until then you can edit `blog/server.js` to change that.
